import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import {Glyph,Empty} from './WorkspaceUI';
type ResumeVersion={id:string;name:string;createdAt:string;jdUrl:string;jdText:string;prompt:string;resumeText:string;baseFile:File|null};
type ResumeProfile={id:string;name:string;versions:ResumeVersion[]};

const blank={name:'',jdUrl:'',jdText:'',prompt:'',resumeText:''};
const demoDraft={name:'Java Backend · Sample application',jdUrl:'https://example.com/careers/java-backend',jdText:'SAMPLE JOB DESCRIPTION\n\nWe are looking for a Java Backend Developer to build reliable APIs.\n\nResponsibilities\n• Build REST services with Java and Spring Boot.\n• Work with PostgreSQL and JPA.\n• Write tests and collaborate with product teams.\n\nSkills\nJava, Spring Boot, SQL, Git, and Docker.',prompt:'Focus on Java, Spring Boot, and API design. Keep it concise and easy to scan. Use only experience in my base resume; do not invent skills or achievements.',resumeText:'TAYLOR MORGAN — FICTIONAL DEMO RESUME\nBackend Developer\n\nSUMMARY\nSoftware developer interested in reliable APIs and thoughtful system design.\n\nSKILLS\nJava · Spring Boot · PostgreSQL · JPA · Docker\n\nEXPERIENCE\nDemo Projects — Backend Developer\n• Built a sample knowledge management API.\n• Implemented persistence with JPA and PostgreSQL.\n• Added validation and integration tests.\n\nEDUCATION\nSample Computer Science degree'};
const demoProfiles:ResumeProfile[]=[
 {id:'java',name:'Java Backend',versions:[{...demoDraft,id:'java-v2',name:'API Developer · Version 2',createdAt:'2026-10-02T10:00:00Z',baseFile:null},{...demoDraft,id:'java-v1',name:'General Backend · Version 1',createdAt:'2026-10-01T10:00:00Z',baseFile:null}]},
 {id:'ai',name:'AI / ML',versions:[{...demoDraft,id:'ai-v1',name:'RAG Engineer · Version 1',createdAt:'2026-10-01T12:00:00Z',jdUrl:'',jdText:'SAMPLE JD: AI engineer working on retrieval, evaluation, and Python services.',resumeText:'FICTIONAL DEMO RESUME\nAI / ML profile\n\nSKILLS\nPython · Retrieval · Evaluation\n\nPROJECTS\nBuilt a sample document retrieval and evaluation prototype.',prompt:'Highlight retrieval and evaluation projects. Keep the resume to one page.',baseFile:null}]},
 {id:'fullstack',name:'Full Stack',versions:[{...demoDraft,id:'fullstack-v1',name:'Full Stack · Version 1',createdAt:'2026-09-30T14:00:00Z',jdUrl:'',jdText:'SAMPLE JD: Full stack developer building React interfaces and Java APIs.',resumeText:'FICTIONAL DEMO RESUME\nFull Stack profile\n\nSKILLS\nReact · TypeScript · Java\n\nPROJECTS\nBuilt a sample responsive web application with a Java API.',prompt:'Balance frontend and backend work. Emphasize accessible interfaces.',baseFile:null}]}
];
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function ResumeBuilder({onDirtyChange}:{onDirtyChange:(dirty:boolean)=>void}){
 const [profiles,setProfiles]=useState<ResumeProfile[]>(demoProfiles);const [selected,setSelected]=useState('java');
 const [draft,setDraft]=useState(demoDraft);const [baseFile,setBaseFile]=useState<File|null>(null);
 const [folderName,setFolderName]=useState('');const [dirty,setDirty]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const profile=profiles.find(item=>item.id===selected);
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function edit(field:keyof typeof blank,value:string){setDraft(current=>({...current,[field]:value}));setDirty(true);setMessage('');}
 function clearDraft(){setDraft(blank);setBaseFile(null);setDirty(false);setError('');setMessage('');}
 function selectProfile(id:string){if(dirty){setError('Save your version or clear the draft before switching profiles.');return;}setSelected(id);clearDraft();}
 function addProfile(event:FormEvent){event.preventDefault();const name=folderName.trim();if(!name)return;if(profiles.some(item=>item.name.toLowerCase()===name.toLowerCase())){setError('A profile with that name already exists.');return;}setError('');const next=[...profiles,{id:crypto.randomUUID(),name,versions:[]}];setProfiles(next);setFolderName('');if(!dirty){setSelected(next[next.length-1].id);clearDraft();}setMessage('Demo profile folder added. Changes reset when this page is reopened.');}
 async function attach(file:File|undefined){if(!file)return;setError('');if(file.size>10*1024*1024){setError('Please choose a base resume smaller than 10 MB.');return;}if(!/\.(pdf|docx|txt|md)$/i.test(file.name)){setError('Choose a PDF, DOCX, TXT, or Markdown resume.');return;}setBaseFile(file);setDirty(true);setMessage('');if(/\.(txt|md)$/i.test(file.name)){try{const text=await file.text();setDraft(current=>({...current,resumeText:current.resumeText||text}));}catch{setError('The file is attached, but its text could not be read. You can paste the resume text below.');}}}
 function openVersion(version:ResumeVersion){if(dirty){setError('Save your version or clear the draft before opening another version.');return;}setDraft({name:version.name,jdUrl:version.jdUrl,jdText:version.jdText,prompt:version.prompt,resumeText:version.resumeText});setBaseFile(version.baseFile);setError('');setMessage('Viewing '+version.name+'. Changes will be saved as a new version.');}
 function saveVersion(event:FormEvent){event.preventDefault();if(!profile)return;setError('');setMessage('');if(!draft.jdUrl.trim()&&!draft.jdText.trim()){setError('Add a job description link or paste the job description.');return;}const version:ResumeVersion={...draft,name:draft.name.trim()||'Version '+(profile.versions.length+1),jdUrl:draft.jdUrl.trim(),id:crypto.randomUUID(),createdAt:new Date().toISOString(),baseFile};setProfiles(current=>current.map(item=>item.id===profile.id?{...item,versions:[version,...item.versions]}:item));setDraft(current=>({...current,name:version.name}));setDirty(false);setMessage(version.name+' added to '+profile.name+' for this demo session.');}
 return <>
  <div className="kb-page-heading"><div><span className="kb-overline">YOUR NEXT OPPORTUNITY</span><h1>Resume Builder<span>.</span></h1><p>One profile. Different roles. A version for each opportunity.</p></div><span className="kb-starter-badge"><span/> UI demo</span></div>
  <div className="kb-interview-notice"><Glyph name="briefcase" size={21}/><p><strong>Your resume workspace · Demo</strong><span>Explore sample profiles and resume versions. Changes last only while this section is open. AI generation, JD fetching, and saved storage will be connected later.</span></p></div>
  {error&&<p className="kb-alert" role="alert">{error}</p>}{message&&<p className="kb-success" role="status">{message}</p>}
  <div className="kb-resume-layout">
   <aside className="kb-resume-profiles" aria-label="Resume profile folders"><span className="kb-overline">PROFILE FOLDERS</span><div className="kb-resume-folder-list">{profiles.map(item=><button key={item.id} onClick={()=>selectProfile(item.id)} className={selected===item.id?'selected':''} aria-pressed={selected===item.id}><Glyph name="books" size={18}/><span>{item.name}<small>{item.versions.length} versions</small></span></button>)}</div><section className="kb-resume-versions" aria-labelledby="resume-versions-title"><div className="kb-resume-form-heading"><h2 id="resume-versions-title">Resume versions</h2><span>{profile?.versions.length||0} saved</span></div>{profile?.versions.length?<div>{profile.versions.map(version=><button key={version.id} onClick={()=>openVersion(version)}><Glyph name="note" size={19}/><span><strong>{version.name}</strong><small>{new Date(version.createdAt).toLocaleString('en-GB',{timeZone:'Europe/London',dateStyle:'medium',timeStyle:'short'})} · {version.baseFile?'Base resume attached':'No attachment'}</small></span><Glyph name="arrow" size={17}/></button>)}</div>:<Empty title="Your first version goes here.">Add a JD and save a demo version.</Empty>}</section><form onSubmit={addProfile}><label htmlFor="resume-profile-name">New profile</label><input id="resume-profile-name" placeholder="e.g. Data Engineer" value={folderName} maxLength={80} onChange={e=>setFolderName(e.target.value)} required/><button className="kb-button secondary" disabled={!folderName.trim()}><Glyph name="plus" size={15}/> Add profile</button></form></aside>
   <div className="kb-resume-content"><form className="kb-resume-form" onSubmit={saveVersion}>
    <div className="kb-resume-form-heading"><div><span className="kb-overline">{profile?.name.toUpperCase()}</span><h2>Prepare a resume version</h2></div><span>{dirty?'Unsaved draft':'Ready'}</span></div>
    <label htmlFor="resume-version-name">Version name <small>Optional</small></label><input id="resume-version-name" placeholder="e.g. Backend role · Company name" maxLength={120} value={draft.name} onChange={e=>edit('name',e.target.value)}/>
    <div className="kb-resume-step"><span>01</span><h3>Job description</h3></div><label htmlFor="resume-jd-url">JD link</label><input id="resume-jd-url" type="url" placeholder="https://company.com/careers/role" maxLength={2000} value={draft.jdUrl} onChange={e=>edit('jdUrl',e.target.value)}/>
    <label htmlFor="resume-jd-text">Or paste the job description</label><textarea id="resume-jd-text" placeholder="Responsibilities, required skills, and experience…" rows={5} maxLength={50000} value={draft.jdText} onChange={e=>edit('jdText',e.target.value)}/>
    <div className="kb-resume-step"><span>02</span><h3>Base resume <small>Optional</small></h3></div><label className="kb-resume-upload" htmlFor="resume-base-file"><Glyph name="note" size={24}/><strong>{baseFile?baseFile.name:'Choose a base resume'}</strong><span>PDF, DOCX, TXT, or Markdown · up to 10 MB</span><input id="resume-base-file" type="file" accept=".pdf,.docx,.txt,.md" onChange={event=>{void attach(event.target.files?.[0]);event.target.value='';}}/></label>
    {baseFile&&<div className="kb-resume-file-actions"><button type="button" onClick={()=>download(baseFile,baseFile.name)}>Download attached resume</button><button type="button" onClick={()=>{setBaseFile(null);setDirty(true);setMessage('');}}>Remove attachment</button></div>}
    <p className="kb-muted">Text files fill the editor when it is empty. PDF and DOCX files are kept as attachments; paste their text below to edit it.</p>
    <label htmlFor="resume-content">Resume text / draft</label><textarea id="resume-content" placeholder="Paste your existing resume or start writing here. No base resume is required." rows={8} maxLength={100000} value={draft.resumeText} onChange={e=>edit('resumeText',e.target.value)}/>
    <div className="kb-resume-step"><span>03</span><h3>Your instructions</h3></div><label htmlFor="resume-prompt">Specific prompt for the resume builder</label><textarea id="resume-prompt" placeholder="e.g. Focus on Java and Spring Boot, keep it to two pages, and use only experience from my base resume." rows={4} maxLength={10000} value={draft.prompt} onChange={e=>edit('prompt',e.target.value)}/><p className="kb-muted">Your prompt is saved with this version for future AI generation.</p>
    <div className="kb-resume-actions"><button className="kb-button" disabled={!profile}>Save demo version<Glyph name="check" size={16}/></button><button type="button" className="kb-button secondary" disabled={!draft.resumeText.trim()} onClick={()=>download(new Blob([draft.resumeText],{type:'text/plain;charset=utf-8'}),(profile?.name||'resume').replace(/[^a-z0-9-]/gi,'-')+'.txt')}>Download draft</button><button type="button" className="kb-resume-clear" onClick={clearDraft}>Clear draft</button></div>
   </form>

   </div>
  </div>
 </>;
}
